### ISSUE TITLE
Structure of token.json

### ISSUE THREAD

**Issue by Killians06** [ElBenedictus/amongus-discord-proximity#1]
Hey mate !
Can you give us the structure on token.json file please ?

**Comment by ElBenedictus** [comment]
Hi, the _token.json_ file looks like this.
`{ 
	"botFather": "here token of a discord bot....",  
    "botChild": [  
        "here token of a discord bot....",  
        "here token of a discord bot...._",  
        ....
    ],
    "playerSimulator": [
        "here token of a discord bot....",
        "here token of a discord bot...."
    ]
}`
Don't put too much faith in this project, I quickly abandoned it. Discord bots don't really allow you to do that kind of thing.

**Comment by Killians06** [comment]
Thanks !
How many bots did you create ?
10 for each "collections" ?

**Comment by ElBenedictus** [comment]
There are 2 bots per channel: a "microphone" and a "speaker". They are the "botChild". I had planned 10 players, so 10 channels, so 20 child bots. 
There are also 2 "playerSimulator" which allowed me to make tests.
And a bot "botFather" which manages the whole.
